
###
GET http://localhost:3005/tickers/
Content-Type: application/json

###
GET http://localhost:3005/
Content-Type: application/json

###
GET http://localhost:3005/quotes
Content-Type: application/json
###

GET http://localhost:3005/quotes/2020-04-08T21:00:00.000Z
Content-Type: application/json
###

GET http://localhost:3005/quotes/2020-04-08T21:00:00.000Z?skip=1&limit=6
Content-Type: application/json
###
